### ISSUE TITLE
net.starschema.clouddb.jdbc.JdbcGrammarParser is not in the code

### ISSUE THREAD

**Issue by aresetian** [jonathanswenson/starschema-bigquery-jdbc#5]
When I try to compile the code, this not compiled because of the class net.starschema.clouddb.jdbc.JdbcGrammarParser is not in the project , the same problem happend if I download the code from https://code.google.com/p/starschema-bigquery-jdbc/source/browse/. Any idea how to find this class so as to compile the project.

**Comment by jonathanswenson** [comment]
@aresetian net.starschema.clouddb.jdbc.JdbcGrammarParser as well as a few other resources are built from the antlr grammars included in the project. I recently added the antlr-maven plugin that will build these dependencies automatically during the maven build process. Using `mvn package` or `mvn compile` should build these for you. 

You will probably have to run with the `-Dmaven.test.skip=true` flag until you can get the tests passing. This requires some non-trivial setup. I hope to add all this information to a readme in the near future.
